# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, mymaster ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo Hello, world!

    - name: info
      run: |
        perl -v
        bash --version
        env | sort
